name: air_state
description: A lightweight, modular state management library for the Air Framework.
version: 1.0.5
homepage: https://github.com/AndreyDAraya/air-state
repository: https://github.com/AndreyDAraya/air-state

environment:
  sdk: ^3.10.8

topics:
  - state-management
  - reactive
  - flutter
  - air

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
